### PR TITLE
Add goals data into Goals table

### PR DESCRIPTION
**Pull request by snipe**
This is a partial fix for #1.

### CODE REVIEW

**Comment by snipe** [comment]
Not sure how I can address the coveralls issue, since the test already exists to check if the goals table exists. :(

**Comment by jenssegers** [comment]
Goals should be automatically created on the fly, but it makes sense to populate them in advance.

**Comment by snipe** [comment]
Well, they weren't being created on the fly in the latest release, so I figured this might be a good start if you specified goals in the config at the start. 

I'd love to learn more about how you intended this to work so I can provide useful pull requests. I don't want to waste your time with dumb questions, but I'd love to help you with this package.

**Comment by jenssegers** [comment]
The reason the unittest is failing is because goals have a compound primary key of goal name and experiment. So for each experiment, there needs to be a row for each goal that has the number of views.

**Comment by jenssegers** [comment]
Goals are now populated during the install command.

Maybe I should move the database schema stuff to a proper migration class.

**Pull request merged**
